### PR TITLE
Universal definition

### PR DESCRIPTION
**Pull request by ryanburnette**
- [x] universal definition to support two varieties of module loader as well as loading right to the window
- [x] .jshintrc
- [ ] haven't been able to get the tests to pass, but I'm pretty sure it's an issue with the test
- [ ] versions sits at 1.0.2 in the pr

### CODE REVIEW

**Comment by ryanburnette** [comment]
@kyungw00k 

Did you notice that the tests are still failing?

**Comment by kyungw00k** [comment]
@ryanburnette 

Hmm... document size is too small to scroll down, actually it doesn't have scroll. 

https://github.com/kyungw00k/window-scroll-position/pull/1/commits/ff6617134e9b99fee8f49563d42591c441519cfe

Do you have a reason why you had change document size to 100x100 instead?

**Comment by ryanburnette** [comment]
It didn’t work at 30,000 either. I changed the size to play around and it
still failed.

I was going to try a set timeout to see if it was a timing thing, but the
tests you’re doing are unfamiliar to me.

It looks like the tests were failing on your last release too. I know the
library works. I just think the test is broken.

**Comment by kyungw00k** [comment]
@ryanburnette 

Hmm, I think the test case should be made more accurate.

I'll look into it.

Thanks!

**Pull request merged**
